name: 'Action MeasureSoftGram'
description: 'Use the product MeasureSoftGram and show the results in the pull requests.'
inputs:
  host:
    description: "SonarQube Server URL"
    required: false
  sonartoken:
    description: "Sonarqube token"
    required: false
  projectKey:
    description: "Sonarqube project key. The default key will be 'owner-repository'."
    required: false
    default: ""
  githubToken:
    description: "Github token. https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret"
    required: true
  productName:
    description: "Product name"
    required: true
  msgramServiceToken:
    required: true
    description: "Token to access the MeasureSoftGram service"
runs:
  using: 'node16'
  main: 'dist/index.js'